default:
  golem_name: nunatsiavutBirdTracker
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
  timeout_session_time: 300
  timeout_closing_time: 30
dev:
  golem_wd: !expr golem::pkg_path()
  timeout_session_time: 60
  timeout_closing_time: 10
