# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release-event-release
# Trigger the create release workflow
on:
  push:
    branches: main
  pull_request:
    branches: main

name: Build docker image

jobs:
  push_to_registry:
    name: Build and push docker image
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Decode Google API key file
        env:
          BASE64_STRING: ${{ secrets.GOOGLE_API_KEY_BASE64 }}
        run: echo $BASE64_STRING > google_api_key.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_API_KEY_BASE64 }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker for GCR
        run: gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            gcr.io/my_project/my_app:latest
            gcr.io/my_project/my_app:${{ env.GITHUB_TAG }}
          file: ./Dockerfile
          push: true
