# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release-event-release
# Trigger the create release workflow
on:
  push:
    branches: main
  pull_request:
    branches: main

name: Build docker image

jobs:
  push_to_registry:
    name: Build docker image
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
